// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: operator/validatorpb/validator.proto

package validatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkEncodingFormat int32

const (
	ChunkEncodingFormat_UNKNOWN ChunkEncodingFormat = 0
	ChunkEncodingFormat_GNARK   ChunkEncodingFormat = 1
)

// Enum value maps for ChunkEncodingFormat.
var (
	ChunkEncodingFormat_name = map[int32]string{
		0: "UNKNOWN",
		1: "GNARK",
	}
	ChunkEncodingFormat_value = map[string]int32{
		"UNKNOWN": 0,
		"GNARK":   1,
	}
)

func (x ChunkEncodingFormat) Enum() *ChunkEncodingFormat {
	p := new(ChunkEncodingFormat)
	*p = x
	return p
}

func (x ChunkEncodingFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkEncodingFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_validatorpb_validator_proto_enumTypes[0].Descriptor()
}

func (ChunkEncodingFormat) Type() protoreflect.EnumType {
	return &file_operator_validatorpb_validator_proto_enumTypes[0]
}

func (x ChunkEncodingFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkEncodingFormat.Descriptor instead.
func (ChunkEncodingFormat) EnumDescriptor() ([]byte, []int) {
	return file_operator_validatorpb_validator_proto_rawDescGZIP(), []int{0}
}

type GetChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobKey       []byte                 `protobuf:"bytes,1,opt,name=blob_key,json=blobKey,proto3" json:"blob_key,omitempty"`
	QuorumId      uint32                 `protobuf:"varint,2,opt,name=quorum_id,json=quorumId,proto3" json:"quorum_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunksRequest) Reset() {
	*x = GetChunksRequest{}
	mi := &file_operator_validatorpb_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunksRequest) ProtoMessage() {}

func (x *GetChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_validatorpb_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunksRequest.ProtoReflect.Descriptor instead.
func (*GetChunksRequest) Descriptor() ([]byte, []int) {
	return file_operator_validatorpb_validator_proto_rawDescGZIP(), []int{0}
}

func (x *GetChunksRequest) GetBlobKey() []byte {
	if x != nil {
		return x.BlobKey
	}
	return nil
}

func (x *GetChunksRequest) GetQuorumId() uint32 {
	if x != nil {
		return x.QuorumId
	}
	return 0
}

type GetChunksReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Chunks              [][]byte               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ChunkEncodingFormat ChunkEncodingFormat    `protobuf:"varint,2,opt,name=chunk_encoding_format,json=chunkEncodingFormat,proto3,enum=validator.ChunkEncodingFormat" json:"chunk_encoding_format,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetChunksReply) Reset() {
	*x = GetChunksReply{}
	mi := &file_operator_validatorpb_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunksReply) ProtoMessage() {}

func (x *GetChunksReply) ProtoReflect() protoreflect.Message {
	mi := &file_operator_validatorpb_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunksReply.ProtoReflect.Descriptor instead.
func (*GetChunksReply) Descriptor() ([]byte, []int) {
	return file_operator_validatorpb_validator_proto_rawDescGZIP(), []int{1}
}

func (x *GetChunksReply) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *GetChunksReply) GetChunkEncodingFormat() ChunkEncodingFormat {
	if x != nil {
		return x.ChunkEncodingFormat
	}
	return ChunkEncodingFormat_UNKNOWN
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_operator_validatorpb_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_validatorpb_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_operator_validatorpb_validator_proto_rawDescGZIP(), []int{2}
}

type GetNodeInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semver        string                 `protobuf:"bytes,1,opt,name=semver,proto3" json:"semver,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	NumCpu        uint32                 `protobuf:"varint,4,opt,name=num_cpu,json=numCpu,proto3" json:"num_cpu,omitempty"`
	MemBytes      uint64                 `protobuf:"varint,5,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoReply) Reset() {
	*x = GetNodeInfoReply{}
	mi := &file_operator_validatorpb_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoReply) ProtoMessage() {}

func (x *GetNodeInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_operator_validatorpb_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoReply.ProtoReflect.Descriptor instead.
func (*GetNodeInfoReply) Descriptor() ([]byte, []int) {
	return file_operator_validatorpb_validator_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeInfoReply) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

func (x *GetNodeInfoReply) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *GetNodeInfoReply) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetNodeInfoReply) GetNumCpu() uint32 {
	if x != nil {
		return x.NumCpu
	}
	return 0
}

func (x *GetNodeInfoReply) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

var File_operator_validatorpb_validator_proto protoreflect.FileDescriptor

const file_operator_validatorpb_validator_proto_rawDesc = "" +
	"\n" +
	"$operator/validatorpb/validator.proto\x12\tvalidator\"J\n" +
	"\x10GetChunksRequest\x12\x19\n" +
	"\bblob_key\x18\x01 \x01(\fR\ablobKey\x12\x1b\n" +
	"\tquorum_id\x18\x02 \x01(\rR\bquorumId\"|\n" +
	"\x0eGetChunksReply\x12\x16\n" +
	"\x06chunks\x18\x01 \x03(\fR\x06chunks\x12R\n" +
	"\x15chunk_encoding_format\x18\x02 \x01(\x0e2\x1e.validator.ChunkEncodingFormatR\x13chunkEncodingFormat\"\x14\n" +
	"\x12GetNodeInfoRequest\"\x84\x01\n" +
	"\x10GetNodeInfoReply\x12\x16\n" +
	"\x06semver\x18\x01 \x01(\tR\x06semver\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x17\n" +
	"\anum_cpu\x18\x04 \x01(\rR\x06numCpu\x12\x1b\n" +
	"\tmem_bytes\x18\x05 \x01(\x04R\bmemBytes*-\n" +
	"\x13ChunkEncodingFormat\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05GNARK\x10\x012\x9b\x01\n" +
	"\tRetrieval\x12C\n" +
	"\tGetChunks\x12\x1b.validator.GetChunksRequest\x1a\x19.validator.GetChunksReply\x12I\n" +
	"\vGetNodeInfo\x12\x1d.validator.GetNodeInfoRequest\x1a\x1b.validator.GetNodeInfoReplyB>Z<github.com/eigenda-blob-observer/prober/operator/validatorpbb\x06proto3"

var (
	file_operator_validatorpb_validator_proto_rawDescOnce sync.Once
	file_operator_validatorpb_validator_proto_rawDescData []byte
)

func file_operator_validatorpb_validator_proto_rawDescGZIP() []byte {
	file_operator_validatorpb_validator_proto_rawDescOnce.Do(func() {
		file_operator_validatorpb_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operator_validatorpb_validator_proto_rawDesc), len(file_operator_validatorpb_validator_proto_rawDesc)))
	})
	return file_operator_validatorpb_validator_proto_rawDescData
}

var file_operator_validatorpb_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operator_validatorpb_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_operator_validatorpb_validator_proto_goTypes = []any{
	(ChunkEncodingFormat)(0),   // 0: validator.ChunkEncodingFormat
	(*GetChunksRequest)(nil),   // 1: validator.GetChunksRequest
	(*GetChunksReply)(nil),     // 2: validator.GetChunksReply
	(*GetNodeInfoRequest)(nil), // 3: validator.GetNodeInfoRequest
	(*GetNodeInfoReply)(nil),   // 4: validator.GetNodeInfoReply
}
var file_operator_validatorpb_validator_proto_depIdxs = []int32{
	0, // 0: validator.GetChunksReply.chunk_encoding_format:type_name -> validator.ChunkEncodingFormat
	1, // 1: validator.Retrieval.GetChunks:input_type -> validator.GetChunksRequest
	3, // 2: validator.Retrieval.GetNodeInfo:input_type -> validator.GetNodeInfoRequest
	2, // 3: validator.Retrieval.GetChunks:output_type -> validator.GetChunksReply
	4, // 4: validator.Retrieval.GetNodeInfo:output_type -> validator.GetNodeInfoReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operator_validatorpb_validator_proto_init() }
func file_operator_validatorpb_validator_proto_init() {
	if File_operator_validatorpb_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_validatorpb_validator_proto_rawDesc), len(file_operator_validatorpb_validator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_validatorpb_validator_proto_goTypes,
		DependencyIndexes: file_operator_validatorpb_validator_proto_depIdxs,
		EnumInfos:         file_operator_validatorpb_validator_proto_enumTypes,
		MessageInfos:      file_operator_validatorpb_validator_proto_msgTypes,
	}.Build()
	File_operator_validatorpb_validator_proto = out.File
	file_operator_validatorpb_validator_proto_goTypes = nil
	file_operator_validatorpb_validator_proto_depIdxs = nil
}
