syntax = "proto3";
package validator;
option go_package = "github.com/eigenda-blob-observer/prober/operator/validatorpb";

service Retrieval {
  rpc GetChunks(GetChunksRequest) returns (GetChunksReply);
  rpc GetNodeInfo(GetNodeInfoRequest) returns (GetNodeInfoReply);
}

message GetChunksRequest {
  bytes blob_key = 1;
  uint32 quorum_id = 2;
}

message GetChunksReply {
  repeated bytes chunks = 1;
  ChunkEncodingFormat chunk_encoding_format = 2;
}

enum ChunkEncodingFormat {
  UNKNOWN = 0;
  GNARK = 1;
}

message GetNodeInfoRequest {}

message GetNodeInfoReply {
  string semver = 1;
  string arch = 2;
  string os = 3;
  uint32 num_cpu = 4;
  uint64 mem_bytes = 5;
}
